- Xamarin.MacDev/IPhoneDeviceType.cs
- Xamarin.MacDev/Keychain.cs
Low-level changes required for https://github.com/xamarin/md-addins/pull/1836
* Add GetKeychainPath method
* Add iPod to the list of Apple device families
* Add GetDeviceClass extension method for AppleDeviceFamily enum
> New signing panel

- Xamarin.MacDev/IPhoneDeviceType.cs
- Xamarin.MacDev/Keychain.cs
Keychain:
* Add GetKeychainPath method
AppleDeviceFamily:
* Add iPod to the list device families
* Add `AppleDeviceFamilyExtensions.GetDeviceClass` it returnes string represnetation of `AppleDeviceFamily` enum members.
> Keychain and AppleDeviceFamily updates

- Xamarin.MacDev/MacOSXSdkVersion.cs
macOS High Sierra 10.13 definitions.
> High Sierra

- Xamarin.MacDev/MobileProvisionIndex.cs
They were supposed to be reverse sorted by CreationDate.
Also added failure reporting for GetMobileProvision()
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=60377
> Fixed sorting of Provisioning Profiles in the Index

- Xamarin.MacDev/EntitlementExtensions.cs
Add missing data protection entitlement key
> Add missing data protection entitlement key

- Xamarin.MacDev/EntitlementExtensions.cs
Both will be used to get entitlements telemetry.
> Add AllKeys property and GetEntitlementsKeys method

- Xamarin.MacDev/EntitlementExtensions.cs
It's precisely what the title says. Only one line of change in this PR.
> Add NFC entitlement key to EntitlementKeys

- Xamarin.MacDev/EntitlementExtensions.cs
> Add ClassKit entitlement key

- Xamarin.MacDev/EntitlementExtensions.cs
Back port of Xcode 9.4 preview features to 15-7 release branch
> Add ClassKit entitlements key

- Xamarin.MacDev/EntitlementExtensions.cs
VSTS: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/692176
> VSTS-692176: Add missing AutoFill Credential Provider entitlement

- Xamarin.MacDev/IPhoneImageSizes.cs
Backport of https://github.com/xamarin/Xamarin.MacDev/pull/35
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/702327
> VSTS 702327: d15-9

- Xamarin.MacDev/EntitlementExtensions.cs
Backport https://github.com/xamarin/Xamarin.MacDev/pull/44
> Add entitlement keys for Hardened Runtime

- Xamarin.MacDev/MonoTouchSdk.cs
- Xamarin.MacDev/XamMacSdk.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935384
> [vsts-935384] Remove SupportsSGenConcurrentGCExperimental from SDKs

- Xamarin.MacDev/ManifestExtensions.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/904676
> [vsts-904676] Add multiple screens manifest keys

- Xamarin.MacDev/ManifestExtensions.cs
https://github.com/xamarin/vsmac-xamarin-extensions/pull/295
> Backport required for vsmac-xamarin-extensions/pull/295

- Xamarin.MacDev/MonoTouchSdk.cs
Related PRs:
https://github.com/xamarin/vsmac-xamarin-extensions/pull/283
https://github.com/xamarin/xamarin-macios/pull/6791
> [vsts-938452] Add `altool` feature support

- Xamarin.MacDev/ManifestExtensions.cs
- Xamarin.MacDev/MonoTouchSdk.cs
* Add credential provider to ExtensionPoint enumeration
* Add min version check rule for credential provider ExtensionPoint
* Add trailing comma to make the next entry's diff smaller
> [xcode12] Add AutoFill CredentialProvider NSExtensionPoint support (#75)

- Xamarin.MacDev/MobileProvisionIndex.cs
For Windows, the file was stored on the Documents folder and we don't store anything in there but in %LocalAppData%\Xamarin
> Set IndexFileName based on the current OS platform

- Xamarin.MacDev/PListObject.cs
This is referenced on AB#1188585 and AB#1198008
> Updating comment for policheck

- Xamarin.MacDev/ManifestExtensions.cs
Adding new extension methods to ManifestExtension class to support this [task](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1590703).
> Adding new extension methods to ManifestExtensions class

- Xamarin.MacDev/EntitlementExtensions.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1564705
Added keys for new entitlements
> Added new entitlements for Xcode14

- CODE-OF-CONDUCT.md
Ref: https://github.com/dotnet/org-policy-violations/issues/5661
> Add a Code of Conduct.
