- Xamarin.MacDev/ManifestExtensions.cs
This lets us get the actual extension point key which is needed for the XI Versions.plist file.
> Add GetNSExtensionPointIdentifier

- Xamarin.MacDev/Keychain.cs
This overload allows to search for keychain internet passwords
by one of these properties(or their combinations):
* server name
* security domain
* path
* port
* account name
> Add Keychain.FindInternetPassword overload

- Xamarin.MacDev/AppleSdkSettings.cs
- Xamarin.MacDev/MonoTouchSdk.cs
- Xamarin.MacDev/XamMacSdk.cs
This lets the IDE explain in the About section, the exact reason it couldn't load
a given SDK.
Also includes some log message refinements.
> [iOS/Mac] Add SdkNotInstalledReason

- Xamarin.MacDev/PListObject.cs
Task.StartNew can run on any thread depending on who is
invoking it. What we want is to run on a background thread,
so we should use Task.Run.
Alternatively we can use Task.StartNew (..., TaskScheduler.Default);
but it is cleaner and simpler to use `Run`.
> Use the right `Task` method to run on a background thread

- Xamarin.MacDev/AppleSdk.cs
- Xamarin.MacDev/AppleSdkSettings.cs
- Xamarin.MacDev/MonoMacSdk.cs
- Xamarin.MacDev/MonoTouchSdk.cs
Instead of just using `File.GetLastWriteTime`.
Fixes bug #51694: Use File.GetLastWriteTimeUtc not File.GetLastWriteTime
https://bugzilla.xamarin.com/show_bug.cgi?id=51694
> [iOS] Only use File.GetLastWriteTimeUtc

- Xamarin.MacDev/MobileProvisionIndex.cs
- Xamarin.MacDev/PListObject.cs
This patch doesn't "fix" existing indexes to be sorted by
CreationDate, but if/when any new records are added, the
index will get sorted.
The advantage of sorting by CreationDate allows us to avoid
calling MobileProvision.Load() for anything but the *latest*
version of a provisioning profile when 'unique' is 'true'.
Since 'unique' is always 'true' in the iOS Bundle Signing
Project Options, this could theoretically improve performance
if the user has a bunch of duplicate provisioning profiles
(which can happen if devices and/or developers have been
added/removed from a provisioning profile, the entitlements
have changed, or if the provisioning profile has been renewed).
*May* fix https://bugzilla.xamarin.com/show_bug.cgi?id=54150
> Sort MobileProvisionIndex records by CreationDate

- Xamarin.MacDev/AppleSdkSettings.cs
We have a `SetInvalid` step which empties `DeveloperRoot`.
This is problematic later on to retrive the guilty (wrong) Xcode path
so saving it as InvalidDeveloperRoot.
> Add InvalidDeveloperRoot

- Xamarin.MacDev/MobileProvisionIndex.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=58251
> Add support for optionally explaining why inapplicable provisioning profiles are not applicable. Partially fixes #58251.

- Xamarin.MacDev/EntitlementExtensions.cs
Need these changes in d15-6 to report more detailed telemetry about entitlements.
> D15 6 entitlements

- Xamarin.MacDev/IPhoneImageSizes.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/702327
> VSTS 702327: Launch image sizes for iPhone XS Max and iPhone XR

- Xamarin.MacDev/Xamarin.MacDev.csproj
- Xamarin.MacDev/Xamarin.iOSDev.csproj
We'll be using MicroBuild to sign all the binaries built in AzDO. This repository is a submodule of other projects (e.g. https://github.com/xamarin/profiler) that require MicroBuild to be listed in all nested .csprojs.
This should not negatively affect local/CI builds; the only noticeable change should be that an extra .nupkg (MicroBuild.Core) is downloaded during build.
> Add in MicroBuild to all projects for signing

- Xamarin.MacDev/PListObject.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/5277.
> Keys in property list dictionaries aren't necessarily unique. Fixes xamarin-macios#5277.

- Xamarin.MacDev/PListObject.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/5277.
> [d16-0] Keys in property list dictionaries aren't necessarily unique. Fixes xamarin-macios#5277. (#39)

- Xamarin.MacDev/PListObject.cs
Fixes https://github.com/xamarin/xamarin-macios/issues/5277.
> [d15-9] Keys in property list dictionaries aren't necessarily unique. Fixes xamarin-macios#5277. (#39)

- Xamarin.MacDev/IPhoneArchitecture.cs
Context: https://github.com/mono/mono/issues/10641
> Add ARM64_32 to the list of supported architectures

- Xamarin.MacDev/MacOSXSdk.cs
- Xamarin.MacDev/MacOSXSdkVersion.cs
Added 10.14 and 10.15 to list of Mac OS versions.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1003788/
> Bug 1003788: 10.14 missing from target Mac OS version drop-down menu

- Xamarin.MacDev/AppleSdkSettings.cs
Fixes:
> AppleSdkSettings.cs(291,30): warning CS0067: The event 'AppleSdkSettings.Changed' is never used
> Make methods that do nothing obsolete and fix a compiler warning.

- Xamarin.MacDev/MonoTouchSdk.cs
nuget doesn't like files that start with 'build*' in the root nuget directory ([1]), which means we have to support finding the 'buildinfo' file somewhere else too (in particular in 'tools/buildinfo' instead).
[1]: https://github.com/NuGet/Home/issues/8810
> Accept 'tools/buildinfo' as an alternative path to 'buildinfo' due to an nuget bug.

- Xamarin.MacDev/MonoTouchSdk.cs
Adjust SDK validation to find mtouch in a tools/bin directory (which is where
mtouch resides when shipped in a nuget package), and not look in usr/bin
(mtouch hasn't been there in a long, long time, and then it was very briefly).
Simplify the validation logic to output mtouch's actual path instead of a
value indicating the subdirectory where it was found.
Additionally compute the bin directory to be mtouch's directory, and the lib
directory a sibling of the bin directory.
> Adjust SDK validation to allow tools/bin and not allow usr/bin.

- Xamarin.MacDev/AppleSdk.cs
- Xamarin.MacDev/IAppleSdk.cs
- Xamarin.MacDev/IAppleSdkVersion.cs
- Xamarin.MacDev/IPhoneSdkVersion.cs
- Xamarin.MacDev/MacOSXSdk.cs
- Xamarin.MacDev/MacOSXSdkVersion.cs
* Add IAppleSdk interface to bridge AppleSdk and MacOSXSdk.
* Add IAppleSdkVersion interface to bridge IPhoneSdkVersion and MacOXSdkVersion.
> [Xamarin.MacDev] Add interfaces to bridge Xamarin.iOS- and Xamarin.Mac-specific classes.

- Xamarin.MacDev/IAppleSdkVersion.cs
Split IAppleSdkVersion.TryParse into two methods, one that outputs the parsed
int array and one that outputs the actual IAppleSdkVersion. This way we can
re-use the actual version validation by using the int array overload when
we're not interested in the actual version output.
> [Xamarin.MacDev] Split IAppleSdkVersion.TryParse in two methods.

- Xamarin.MacDev/ManifestExtensions.cs
- Xamarin.MacDev/MonoTouchSdk.cs
These commits add support for AutoFill Credential Provider extensions to be built.  A related change to Xamarin.macios is also pending approval of this request.    For more information, see posted issue at: https://github.com/xamarin/xamarin-macios/issues/9000
> Add AutoFill CredentialProvider NSExtensionPoint support

- Xamarin.MacDev/ManifestExtensions.cs
- Xamarin.MacDev/MonoTouchSdk.cs
* Add credential provider to ExtensionPoint enumeration
* Add min version check rule for credential provider ExtensionPoint
* Add trailing comma to make the next entry's diff smaller
> [d16-8] Add AutoFill CredentialProvider NSExtensionPoint support (#75)

- Xamarin.MacDev/LoggingService.cs
This makes it so that logging actually shows up for Xamarin.iOS/Xamarin.Mac
(which does not specify a custom logger).
> Make LoggingService print to the console if there's no custom logger specified.

- Xamarin.MacDev/ManifestExtensions.cs
XSAccentColorAssets will be used as custom key for storing the path to the asset, and NSAccentColorName is the Apple key that contains the name of the asset that will be used as accent color by the OS
> [xcode12] Adds Accent Color manifest keys

- Xamarin.MacDev/AppleSdkSettings.cs
- Xamarin.MacDev/Xamarin.MacDev.csproj
Use what's returned by 'xcode-select -p' as the configured Xcode if none is
specified in Visual Studio's settings. It looks like this was the intention in
the code, but the code that calls 'xcode-select -p' would never execute,
because we'd only run into it if GetConfiguredSdkLocation returned null/empty,
which it never did because it returned the default location
'/Applications/Xcode.app' if nothing was configured in VSfM. With this change,
GetConfiguredSdkLocation will try to get the system's Xcode location
('xcode-select -p') before returning /Applications/Xcode.app.
Also remove /Developer as a default location, Xcode hasn't been there in many,
many years.
Now the order is:
1. Settings in Visual Studio's Preferences.
2. System's Xcode (xcode-select --print-path).
3. …
> Use what's returned by 'xcode-select -p' as the configured Xcode if none is specified in Visual Studio's settings.

- Xamarin.MacDev/AppleSdk.cs
- Xamarin.MacDev/IAppleSdk.cs
- Xamarin.MacDev/MacOSXSdk.cs
And make the MacOSXSdk and AppleSdk classes implement these new methods,
without changing any of the public API in these classes.
This makes it easier to share code between Xamarin.iOS and Xamarin.Mac, since
the IAppleSdk interface can be used in shared code, while the separate classes
can't.
> [Xamarin.MacDev] Add GetAppleDTSettings and GetSdkSettings to the IAppleSdk interface.

- Xamarin.MacDev/MacOSXSdk.cs
We run into this code path on Mac Catalyst.
> [Xamarin.MacDev] Fail gracefully if trying to grab a PList entry from a file that doesn't exist.

- Xamarin.MacDev/AppleSdk.cs
- Xamarin.MacDev/AppleSdkVersion.cs
- Xamarin.MacDev/IAppleSdkVersion.cs
- Xamarin.MacDev/IPhoneSdkVersion.cs
- Xamarin.MacDev/MacOSXSdk.cs
- Xamarin.MacDev/MacOSXSdkVersion.cs
- Xamarin.MacDev/MonoMacSdk.cs
- Xamarin.MacDev/MonoTouchSdk.cs
- Xamarin.MacDev/XamMacSdk.cs
This reduces code duplication and makes it possible to simplify logic in a few places.
> [Xamarin.MacDev] Add an AppleSdkVersion struct which replaces IPhoneSdkVersion and MacOSXSdkVersion.

- Xamarin.MacDev/MacCatalystSupport.cs
- Xamarin.MacDev/MacOSXSdk.cs
This way the code can be included as source in the mtouch/mmp/dotnet-linker projets in xamarin-macios.
> [Xamarin.MacDev] Extract the code to convert between Mac Catalyst versions to a separate file.

- Xamarin.MacDev/MacCatalystSupport.cs
This allows us to construct better error messages.
> [Xamarin.MacDev] Return valid iOS/macOS versions when converting betweeen iOS and macOS versions for Mac Catalyst.

- Xamarin.MacDev/Xamarin.MacDev.csproj
VS projects are now compatible with .NET 4.6.1 so we don't need MacDev.csproj to target 4.5.1 anymore
> Remove net451 target framework from Xamarin.MacDev.csproj

- Xamarin.MacDev/IPhoneDeviceType.cs
Just adding the MacCatlystOptmizedForMac to the method ToDeviceFamily() to support new option.
[1518561](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1518561): [vsm] Add MacCatalyst device family option to the Manifest editor
> Add MacCatlystOptmizedForMac option to ToDeviceFamily()

- Xamarin.MacDev/MonoTouchSdk.cs
As part of the work to support the Info.plist editor on MAUI projects, we need to add the `MacCatalyst` option to this method `GetPlatformKey()`. This method is used to get the key for loading the known SDK versions for the manifest editor as shown in the image below.
> Adding MacCatalyst option to GetPlatformKey()

- Xamarin.MacDev/MonoTouchSdk.cs
This change converts the MacCatalyst known versions to the actual supported versions using the provided map in the `/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/Versions.plist` file.
> Adding support for MacCatalyst versions

- Xamarin.MacDev/Xamarin.MacDev.csproj
There is an issue when building the project Xamarin.MacDev from XamarinVS in the IDE (as a submodule):
This is a known issue with the strongnamer package:
[Add support for multiple frameworks at same time · Issue #58 · dsplaisted/strongnamer (github.com)](https://github.com/dsplaisted/strongnamer/issues/58)
The solution as suggested by @rolfbjarne and @mauroa is to only build XamarinMacDev for net461 on Windows. It is still necessary to build for netstandard2.0 on Mac.
> Only build Xamarin.MacDev for net461 on Windows due to strongnamer issue

- Xamarin.MacDev/ExtendedVersion.cs
- Xamarin.MacDev/XamMacSdk.cs
Having an easy way to access the SDK's is convenient since this information is retrieved by the IDE in the "About VS Mac" section. Rather than having to re-write the parsing code, I prefer on reusing what we already have
These changes simply make use of the already existing code used in MonoTouchSDK: 
https://github.com/xamarin/Xamarin.MacDev/blob/main/Xamarin.MacDev/MonoTouchSdk.cs#L292-L304
I also corrected the fact that we were not parsing for the "Build date" property correctly
> Add Extended Version info to XamMac

- Xamarin.MacDev/AppleSdkSettings.cs
- Xamarin.MacDev/MobileProvision.cs
- Xamarin.MacDev/MobileProvisionIndex.cs
Context: dotnet/runtime#68610
Context: https://github.com/xamarin/xamarin-android-tools/commit/0be567a9
In Mono and .NET prior to .NET 8, the
[`System.Environment.SpecialFolder`][0]`.Personal` enum value would refer to
`$HOME` on Unix platforms.
This will be changing in .NET 8, such that
`Environment.SpecialFolder.Personal` will instead refer to
`$XDG_DOCUMENTS_DIR` (if set) or `$HOME/Documents`.  This is for "semantic
compatibility" with .NET on Windows.
Replace usage of `Environment.SpecialFolder.Personal` with
`Environment.SpecialFolder.UserProfile`, so that our code continues to work as
expected under .NET 8.
[0]: https://docs.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=net-6.0
> Use Environment.SpecialFolder.UserProfile, not SpecialFolder.Personal.

- Xamarin.MacDev/MacCatalystSupport.cs
This way we find the NotNullWhen attribute declared at the bottom of this file.
> Fix build by always including the System.Diagnostics.CodeAnalysis namespace.

- Xamarin.MacDev/AppleSdk.cs
Xcode adds this value to the Info.plist for all builds, so we should also get it
always so that our build can do the same as Xcode.
> [Xamarin.MacDev] Always fetch the DTSDKBuild variable.

- Xamarin.MacDev/MacCatalystSupport.cs
- Xamarin.MacDev/NullableAttributes.cs
This makes it possible for other projects to just include the MacCatalystSupport.cs file without getting the nullability attributes as well.
> [Xamarin.MacDev] Move compatibility nullability attributes to their own file.

- Xamarin.MacDev/AppleSdk.cs
- Xamarin.MacDev/MacOSXSdk.cs
We were accidentally getting the ProductBuildVersion value (which is used for
DTSDKBuild) from the system, not from the SDK used during the build.
This happened because we were trying to Path.Combine two rooted paths - in
which case Path.Combine returns the second path, without combining anything.
The fix is to compute the path of the plist where the ProductBuildVersion
value is located correctly.
Fixing the Path.Combine issue also revealed that the first path passed to
Path.Combine was wrong, so that got fixed too.
And finally make sure we don't Path.Combine two rooted paths anywhere else -
in all other cases we're supposed to just use the second path without
prepending the first, so just remove the Path.Combine call completely in those
cases.
Fixes …
> [Xamarin.MacDev] Fix computing DTSDKBuild. Fixes #xamarin/xamarin-macios@19733.

- Xamarin.MacDev/SQLite.cs
Needed for an internal assessment task.
> Use RandomNumberGenerator instead of System.Random

- Xamarin.MacDev/PListObject.cs
Fixes these warnings:
Xamarin.MacDev/PListObject.cs(1353,7): warning CA2022: Avoid inexact read with 'System.IO.Stream.Read(byte[], int, int)' (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2022)
Xamarin.MacDev/PListObject.cs(1357,7): warning CA2022: Avoid inexact read with 'System.IO.Stream.Read(byte[], int, int)' (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2022)
Xamarin.MacDev/PListObject.cs(1343,6): warning CA2022: Avoid inexact read with 'System.IO.Stream.Read(byte[], int, int)' (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2022)
Xamarin.MacDev/PListObject.cs(1421,6): warning CA2022: Avoid inexact read with 'System.IO.Stream.Read(byte[], int, int)' …
> [Xamarin.MacDev] Use Stream.ReadExactly instead of Stream.Read when we can.

- Xamarin.MacDev/Xamarin.MacDev.csproj
As the Pair to Mac agents in VS are being migrated to target .NET 8, we no longer need to target .NET Framework 4.7.2.
> Stop targeting net472

- UnitTests/TestHelper.cs
- UnitTests/TestMobileProvisionIndex.cs
- Xamarin.MacDev/MobileProvision.cs
- Xamarin.MacDev/MobileProvisionIndex.cs
Starting with Xcode 16, the location of cached provisioning profiles has moved from "~/Library/MobileDevice/Provisioning Profiles" to "~/Library/Developer/Xcode/UserData/Provisioning Profiles"
Fixes https://github.com/xamarin/xamarin-macios/issues/20771
> Updated to use Xcode 16's new provisioning profiles directory

- Xamarin.MacDev/AppleSdkSettings.cs
- Xamarin.MacDev/MobileProvision.cs
- Xamarin.MacDev/MobileProvisionIndex.cs
This is part of the Xamarin deprecation tasks.
The new paths are just used and consumed in this code base. 
The update and migration logic from legacy paths to new paths is handled by the ClientTools.Platform extension. PR: https://dev.azure.com/devdiv/DevDiv/_git/ClientTools.Platform/pullrequest/632938
Par of task: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2428701
> Renamed paths to remove "Xamarin" and start using "maui"

- Xamarin.MacDev/NullableAttributes.cs
- Xamarin.MacDev/PListObject.cs
* A PDictionary can't have null keys, so don't allow that.
* Make a few explicit operators handle null input by returning null.
> [Xamarin.MacDev] A few nullability improvements.

- Xamarin.MacDev/AppleSdkSettings.cs
This way existing tooling can be slowly updated instead of having to update everything all at once.
Example: the provisionator hasn't been updated yet to write to the new path.
> Load the Xcode path from the old xamarin-based Settings.plist path if the new maui-based path doesn't exist.

- Xamarin.MacDev/MobileProvision.cs
Dev17 still generates provisioning information in the legacy Xamarin paths, so we need a way for this code to consider both new and legacy paths. This fixes an issue where Dev17 fails to build with newer iOS SDK versions that relies only on new MAUI paths. The reason of the failure is because Dev17 uses legacy paths and the iOS SDK looks in new paths.
Fixes P0 bug #2505126
> Added backwards compatibility for locating provisioning stuff in legacy Xamarin folders
